# -*- coding: utf-8 -*-
"""Copula-GARCH dash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mLQmVpVsC176cCClUC8lKHGFrRgMpeJ
"""

!pip install arch statsmodels scipy pandas numpy matplotlib seaborn openpyxl -q arch pyvinecopulib networkx arch -q

from google.colab import files

print("Please upload the 'gas_realized.xlsx' file:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f"User uploaded file '{fn}' with length {len(uploaded[fn])} bytes")




# ═════════════════════════════════════════════════════════════════════════════
# 6. DASH APP
# ═════════════════════════════════════════════════════════════════════════════
def _mk_app():
    App = JupyterDash if _HAS_JUPYTER_DASH else Dash
    app = App(__name__)
    hub_opts=[{"label":c,"value":c} for c in ALL_ASSETS]
    default_a=ALL_ASSETS[0]
    default_b=GAS_COL if GAS_COL in ALL_ASSETS else ALL_ASSETS[-1]

    controls=html.Div([
        html.H3("Copula-GARCH",style={"marginBottom":"2px"}),
        html.H3("Mehrdad Heyrani",style={"marginBottom":"2px"}),
        html.Div(DATA_SRC,style={"fontSize":"11px","color":"#777","marginBottom":"14px"}),
        html.Label("Hub 1"),
        dcc.Dropdown(id="hub1",options=hub_opts,value=default_a,clearable=False),
        html.Label("Hub 2",style={"marginTop":"8px"}),
        dcc.Dropdown(id="hub2",options=hub_opts,value=default_b,clearable=False),
        html.Label("GARCH family",style={"marginTop":"8px"}),
        dcc.Dropdown(id="vol",options=[{"label":v,"value":v} for v in _VOL_MAP],
                     value="Standard GARCH",clearable=False),
        html.Label("Innovation distribution",style={"marginTop":"8px"}),
        dcc.Dropdown(id="dist",options=[{"label":v,"value":v} for v in _DIST_MAP],
                     value="Student's t",clearable=False),
        html.Label("Rank corr method",style={"marginTop":"8px"}),
        dcc.Dropdown(id="rmethod",options=[{"label":"Kendall's τ","value":"kendall"},
                     {"label":"Spearman's ρ","value":"spearman"}],value="kendall",clearable=False),
        html.Button("▶ Run analysis",id="run",n_clicks=0,
            style={"marginTop":"16px","width":"100%","padding":"10px",
                   "background":"#1f77b4","color":"white","border":"none",
                   "borderRadius":"6px","fontSize":"14px","cursor":"pointer"}),
        html.Div(id="status",style={"marginTop":"10px","fontSize":"12px","color":"#555"}),
    ],style={"width":"250px","padding":"18px","background":"#f7f9fc",
             "height":"100vh","boxSizing":"border-box","overflowY":"auto",
             "borderRight":"1px solid #e2e6ea"})

    section1=html.Div([
        dcc.Loading(dcc.Graph(id="fig_corr"),type="default"),
        dcc.Loading(dcc.Graph(id="fig_vol"),type="default"),
        dcc.Loading(dcc.Graph(id="fig_spark"),type="default"),
    ])
    section2=html.Div([
        html.H4("GARCH marginals & PIT summary"),
        dcc.Loading(dash_table.DataTable(id="tbl_marg",
            style_cell={"fontSize":"12px","padding":"6px","textAlign":"center"},
            style_header={"backgroundColor":"#2c3e50","color":"white","fontWeight":"bold"})),
        html.H4("Bivariate copula selection (9 families)",style={"marginTop":"18px"}),
        dcc.Loading(dash_table.DataTable(id="tbl_cop",
            style_cell={"fontSize":"12px","padding":"6px","textAlign":"center"},
            style_header={"backgroundColor":"#2c3e50","color":"white","fontWeight":"bold"},
            style_data_conditional=[{"if":{"filter_query":'{Best} = "★"'},
                "backgroundColor":"#eaf4ff","fontWeight":"bold"}])),
        html.H4("Best-fit copula diagnostics",style={"marginTop":"18px"}),
        dcc.Loading(dcc.Graph(id="fig_diag")),
    ])

    main=html.Div([
        dcc.Tabs([
            dcc.Tab(label="① Rolling EDA",children=[html.Div(section1,style={"padding":"12px"})]),
            dcc.Tab(label="② Model output & diagnostics",children=[html.Div(section2,style={"padding":"12px"})]),
        ]),
    ],style={"flex":"1","padding":"10px","overflowY":"auto","height":"100vh","boxSizing":"border-box"})

    app.layout=html.Div([controls,main],
        style={"display":"flex","fontFamily":"system-ui, sans-serif"})

    # ── EDA callback (fast; updates on Run) ──
    @app.callback(
        Output("fig_corr","figure"),Output("fig_vol","figure"),Output("fig_spark","figure"),
        Input("run","n_clicks"),
        State("hub1","value"),State("hub2","value"),State("rmethod","value"))
    def _eda(n,a,b,method):
        if a==b:
            empty=go.Figure().update_layout(title="Select two different hubs",height=330)
            return empty,empty,empty
        return (rolling_rank_corr_fig(a,b,method=method),
                rolling_vol_fig(a,b), spark_heat_fig(a,b))

    # ── model callback (slow; wrapped in Loading) ──
    @app.callback(
        Output("tbl_marg","data"),Output("tbl_marg","columns"),
        Output("tbl_cop","data"),Output("tbl_cop","columns"),
        Output("fig_diag","figure"),Output("status","children"),
        Input("run","n_clicks"),
        State("hub1","value"),State("hub2","value"),
        State("vol","value"),State("dist","value"))
    def _model(n,a,b,vol,dist):
        if not n:
            return no_update,no_update,no_update,no_update,no_update,"Choose options and press Run."
        if a==b:
            return [],[],[],[],go.Figure(),"⚠ Hub 1 and Hub 2 must differ."
        t0=time.time()
        res=run_model(a,b,vol,dist)
        if not res["ok"]:
            return [],[],[],[],go.Figure(),f"⚠ {res['msg']}"
        mrows=marginal_table(res); crows=copula_table(res)
        mcols=[{"name":k,"id":k} for k in mrows[0].keys()]
        ccols=[{"name":k,"id":k} for k in crows[0].keys()]
        msg=(f"✔ Fitted {vol} · {dist} in {time.time()-t0:.1f}s. "
             f"Best copula: {res['best']['family']} "
             f"(AIC {res['best']['aic']:.1f}).")
        return mrows,mcols,crows,ccols,diagnostics_fig(res),msg

    return app

# ═════════════════════════════════════════════════════════════════════════════
# 7. LAUNCH
# ═════════════════════════════════════════════════════════════════════════════
def run_dashboard(mode="inline", port=8050):
    """
    Launch the dashboard in Colab / Jupyter.
      mode="inline"    → renders inside the notebook cell
      mode="external"  → serves on a port; open via the printed proxy URL
    Works with modern Dash (>=2.11, which has built-in Jupyter support) and with
    the older jupyter-dash package.
    """
    if not _HAS_DASH:
        raise RuntimeError("Install dash first:  pip install dash jupyter-dash plotly")
    app=_mk_app()
    try:
        if _HAS_JUPYTER_DASH:
            # legacy jupyter-dash API
            app.run_server(mode=mode, port=port, height=900)
        else:
            # modern Dash: jupyter_mode handles inline rendering in Colab
            app.run(jupyter_mode=mode, port=port, jupyter_height=900, debug=False)
    except TypeError:
        # very old/new signature fallback
        try:    app.run(port=port, debug=False)
        except Exception: app.run_server(port=port, debug=False)

if __name__=="__main__":
    print(f"Data: {DATA_SRC}  |  assets: {ALL_ASSETS}")
    run_dashboard(mode="inline", port=8050)